auth-server:
  image: java
  ports:
    - "8080:9080"
  volumes:
    - ./auth-server/target/auth-server-0.0.1-snapshot.jar:/opt/auth.jar:rw
  working_dir: /opt
  command: java -jar auth.jar
resource-server:
  image: java
  ports:
    - "8088:9088"
  volumes:
    - ./resource-server/target/resource-server-0.0.1-snapshot.jar:/opt/resource.jar:rw
  working_dir: /opt
  command: java -jar resource.jar
aggregation-server:
  image: java
  ports:
    - "8888:9888"
  volumes:
    - ./aggregation-server/target/aggregation-server-0.0.1-snapshot.jar:/opt/aggregation.jar:rw
  working_dir: /opt
  command: java -jar aggregation.jar
